export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_FINISHED = "LOGIN_FINISHED";
export const LOGIN_REJECTED = "LOGIN_REJECTED";

export const CHANGE_THEME_STARTED = "CHANGE_THEME_STARTED";
export const CHANGE_THEME_FINISHED = "CHANGE_THEME_FINISHED";
export const CHANGE_THEME_REJECTED = "CHANGE_THEME_REJECTED";